##---------------------------------------------------------
## 
## Project #1: TinyFP Representation
##
## March 22, 2018
##
## Jin-Soo Kim (jinsoo.kim@snu.ac.kr)
## Systems Software Laboratory
## Dept. of Computer Science and Engineering
## Seoul National University
##
##---------------------------------------------------------


all:
	gcc -Og -o pa1-test pa1.c pa1-test.c
clean:
	rm -f a.out pa1-test
